# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LCH_manager', '0003_auto_20171022_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='id',
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=28, primary_key=True, serialize=False),
        ),
    ]
