# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LCH_manager', '0004_auto_20171022_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=28)),
                ('surname', models.CharField(max_length=28)),
            ],
            options={
                'verbose_name_plural': 'Coaches',
                'verbose_name': 'Coach',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56)),
                ('year_of_foundation', models.PositiveIntegerField(blank=True, default=None)),
            ],
            options={
                'verbose_name_plural': 'Teams',
                'verbose_name': 'Team',
            },
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Player', 'verbose_name_plural': 'Players'},
        ),
        migrations.AddField(
            model_name='team',
            name='captain',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='LCH_manager.Player'),
        ),
        migrations.AddField(
            model_name='team',
            name='city',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='LCH_manager.City'),
        ),
        migrations.AddField(
            model_name='team',
            name='coach',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='LCH_manager.Coach'),
        ),
    ]
