# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LCH_manager', '0010_auto_20171028_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_a_captain',
            field=models.BooleanField(default=False),
        ),
    ]
