# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LCH_manager', '0012_auto_20171029_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
