# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LCH_manager', '0017_auto_20171030_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='guest_goals_num',
        ),
        migrations.RemoveField(
            model_name='match',
            name='host_goals_num',
        ),
        migrations.AddField(
            model_name='match',
            name='guest_stat',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guests_stats', to='LCH_manager.Statistic'),
        ),
        migrations.AddField(
            model_name='match',
            name='host_stat',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='LCH_manager.Statistic'),
        ),
        migrations.AddField(
            model_name='match',
            name='tour',
            field=models.CharField(blank=True, default=None, max_length=32, null=True),
        ),
    ]
