# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LCH_manager', '0020_statistic_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goalstoplayer',
            options={'verbose_name': 'Goals to player', 'verbose_name_plural': 'Goals to players'},
        ),
        migrations.AlterField(
            model_name='statistic',
            name='position',
            field=models.IntegerField(default=50, null=True),
        ),
    ]
