# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LCH_manager', '0021_auto_20171031_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='id',
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=56, primary_key=True, serialize=False),
        ),
    ]
