# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LCH_manager', '0022_auto_20171031_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='id',
            field=models.IntegerField(default=0),
        ),
    ]
