# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LCH_manager', '0024_auto_20171031_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
