# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LCH_manager', '0025_auto_20171031_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goalstoplayer',
            name='player',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='bombardiers',
        ),
        migrations.RemoveField(
            model_name='match',
            name='guest_stat',
        ),
        migrations.RemoveField(
            model_name='match',
            name='host_stat',
        ),
        migrations.DeleteModel(
            name='GoalsToPlayer',
        ),
        migrations.DeleteModel(
            name='Statistic',
        ),
    ]
