# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LCH_manager', '0028_auto_20171112_2049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventstomatch',
            options={'verbose_name': 'Event in match', 'verbose_name_plural': 'Events in matches'},
        ),
        migrations.AddField(
            model_name='eventstomatch',
            name='match',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='LCH_manager.Match'),
        ),
        migrations.AddField(
            model_name='eventstomatch',
            name='minute',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='eventstomatch',
            name='player',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='LCH_manager.Player'),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Goalkeeper'), (1, 'Defender'), (2, 'Midfielder'), (3, 'Forward')], default=None, null=True),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
