# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LCH_manager', '0029_auto_20171112_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='group',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'A'), (1, 'B'), (2, 'C'), (3, 'D'), (4, 'E'), (5, 'F'), (6, 'G'), (7, 'H')], default=None, null=True),
        ),
    ]
