# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 19:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LCH_manager', '0030_auto_20171112_2136'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
