# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LCH_manager', '0033_auto_20171112_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='group',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D'), (5, 'E'), (6, 'F'), (7, 'G'), (8, 'H')], default=None, null=True),
        ),
    ]
