# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LCH_manager', '0034_auto_20171112_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_in_tournament',
            field=models.BooleanField(default=True),
        ),
    ]
