# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LCH_manager', '0035_team_is_in_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='group',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H')], default=None, max_length=1, null=True),
        ),
    ]
