# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LCH_manager', '0036_auto_20171115_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventstomatch',
            name='event',
            field=models.CharField(choices=[('Goal', 'Goal'), ('Yellow card', 'Yellow card'), ('Red card', 'Red card')], default='Goal', max_length=28),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, choices=[('Goalkeeper', 'Goalkeeper'), ('Defender', 'Defender'), ('Midfielder', 'Midfielder'), ('Forward', 'Forward')], default=None, max_length=28, null=True),
        ),
    ]
