# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LCH_manager', '0037_auto_20171115_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventstomatch',
            name='event',
            field=models.CharField(choices=[('Goal', 'Goal'), ('Yellow card', 'Yellow card'), ('Red card', 'Red card')], max_length=28),
        ),
    ]
