# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LCH_manager', '0038_auto_20171115_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/players/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/teams/'),
        ),
    ]
