# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 22:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LCH_manager', '0042_auto_20171124_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='idd',
        ),
    ]
