# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 22:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LCH_manager', '0044_country_some_int'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='some_int',
        ),
    ]
